FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
ENV OR1K_ARCHIVE=or1k-elf-12.0.1-20220210-20220304.tar.xz
ENV OR1K_RELEASE=or1k-12.0.1-20220210-20220304

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir /ci_build

# Install dependencies
RUN apt update \
    && apt install -y sudo git curl \
      python3 python3-dev python3-venv libffi-dev build-essential \
      gcc-avr avr-libc \
      libnewlib-arm-none-eabi gcc-arm-none-eabi binutils-arm-none-eabi \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install or1k toolchain
RUN --mount=type=cache,target=/ci_cache \
    curl -L https://github.com/openrisc/or1k-gcc/releases/download/${OR1K_RELEASE}/${OR1K_ARCHIVE} \
    -o /ci_cache/${OR1K_ARCHIVE} && \
    tar -xJ -C /ci_build -f /ci_cache/${OR1K_ARCHIVE}

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY . /klipper
WORKDIR /klipper

ENV DICTDIR=/ci_build/dict
RUN uv run ./scripts/ci-build.sh

ENTRYPOINT [ "/bin/uv", "run" ]
CMD [ "py.test" ]
