name: Klipper Container Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # This should mirror the klipper paths-filter in ci-build_test.yaml
    paths:
      - "Makefile"
      - "pyproject.toml"
      - "src/**"
      - "lib/**"
      - "test/configs/**"
      - "scripts/Dockerfile-build"
      - "scripts/buildcommands.py"
      - "scripts/check-gcc.sh"
      - "scripts/ci-build.sh"
      - ".github/workflows/ci-builder.yaml"

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build -f scripts/Dockerfile-build -t dangerklippers/klipper-build:latest .

      - name: Push
        run: docker push dangerklippers/klipper-build:latest
